<?php

namespace Codesquad\Models;

/**
 * UserToken
 * 
 * @package Codesquad\Models
 * @autogenerated by Phalcon Developer Tools
 * @date 2019-06-01, 21:53:13
 */
class UserToken extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     * @Column(column="user_id", type="integer", length=10, nullable=true)
     */
    protected $user_id;

    /**
     *
     * @var string
     * @Column(column="series", type="string", length=255, nullable=true)
     */
    protected $series;

    /**
     *
     * @var string
     * @Column(column="series_hash", type="string", length=255, nullable=true)
     */
    protected $series_hash;

    /**
     *
     * @var string
     * @Column(column="expires_at", type="string", nullable=true)
     */
    protected $expires_at;

    /**
     * Method to set the value of field user_id
     *
     * @param integer $user_id
     * @return $this
     */
    public function setUserId($user_id)
    {
        $this->user_id = $user_id;

        return $this;
    }

    /**
     * Method to set the value of field series
     *
     * @param string $series
     * @return $this
     */
    public function setSeries($series)
    {
        $this->series = $series;

        return $this;
    }

    /**
     * Method to set the value of field series_hash
     *
     * @param string $series_hash
     * @return $this
     */
    public function setSeriesHash($series_hash)
    {
        $this->series_hash = $series_hash;

        return $this;
    }

    /**
     * Method to set the value of field expires_at
     *
     * @param string $expires_at
     * @return $this
     */
    public function setExpiresAt($expires_at)
    {
        $this->expires_at = $expires_at;

        return $this;
    }

    /**
     * Returns the value of field user_id
     *
     * @return integer
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Returns the value of field series
     *
     * @return string
     */
    public function getSeries()
    {
        return $this->series;
    }

    /**
     * Returns the value of field series_hash
     *
     * @return string
     */
    public function getSeriesHash()
    {
        return $this->series_hash;
    }

    /**
     * Returns the value of field expires_at
     *
     * @return string
     */
    public function getExpiresAt()
    {
        return $this->expires_at;
    }

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("codesquad");
        $this->setSource("users_token");
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'users_token';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return UserToken[]|UserToken|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return UserToken|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

}
