version: "3.1"
services:
    mariadb:
      image: mariadb:10.4
      container_name: codesquad-mariadb
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=codesquad
        - MYSQL_USER=codesquad_user
        - MYSQL_PASSWORD=codesquad_password
      ports:
        - "8083:3306"

    webserver:
      image: nginx:alpine
      container_name: codesquad-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: docker/php-fpm
      container_name: codesquad-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/php-fpm/php.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini